runtime: python37
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /static/
  static_dir: static
- url: /oauth2callback
  script: oauth2client.appengine.application
- url: /.*
  script: main.app
